### ISSUE TITLE
Retarget and Reswaping with views 

### ISSUE THREAD

**Issue by CallumBee** [mauricius/laravel-htmx#21]
I am trying to do some re-targeted swapping and looking at the documents I see I can use the retarget and reswap methods and came up with this:

```
return with(new HtmxResponse())->view('components.recipe.ingredient-add-form',[
                'errors' => $validator->errors(),
                'allIngredients' => auth()->user()->ingredients,
            ])->retarget('#ingredientAddForm')->reswap('outerHTML');
```

However it throws a Method Mauricius\LaravelHtmx\Http\HtmxResponse::view does not exist. error. I am still getting my feet wet with Laravel and such so im sure its a me problem and not fully understanding it. Am I doing it right of have I got the wrong end of the stick. 

Thanks

**Comment by mauricius** [comment]
The `HtmxResponse` class doesn't have a `view` method because it's supposed to render only fragments of views, instead of a full view. However I guess you can still return the full view by adding a rendered view to the fragments list, more or less like this (I'm writing by memory)

```php
$view = view()->make('components.recipe.ingredient-add-form', [
  'errors' => $validator->errors(),
  'allIngredients' => auth()->user()->ingredients,
]);

return with(new HtmxResponse())
  ->addRenderedFragment($view)
  ->retarget('#ingredientAddForm')
  ->reswap('outerHTML');
```

**Comment by CallumBee** [comment]
Thanks that makes total sense. I knew it was looking at it all wrong!
