### ISSUE TITLE
Quick question: twig support

### ISSUE THREAD

**Issue by n3storm** [mauricius/laravel-htmx#4]
Do you think this project will support twig usage (with twigbridge) for partial and oob?

Thanks in advance.

**Comment by mauricius** [comment]
No I don't think so. I'm trying to keep the package as much as dependency-free as possible. Perhaps it's possible to implement a plugin architecture to support multiple template engines, but don't have capacity to work on it at the moment.

**Comment by n3storm** [comment]
thanks
