### ISSUE TITLE
Unexpected end of file with nested fragments

### ISSUE THREAD

**Issue by ftinkere** [mauricius/laravel-htmx#5]
Spatie\LaravelIgnition\Exceptions\ViewException: syntax error, unexpected end of file in file /var/www/html/storage/framework/views/6a26dcf6e7e98f66352021016e0241e2.blade.php on line 19

I just put one @fragment block inside other and try to render outside fragment. I thing outside @fragment block connected to inside @endfragment

**Comment by mauricius** [comment]
Fixed in #7
