### ISSUE TITLE
Reinventing fragments

### ISSUE THREAD

**Issue by wizzymore** [mauricius/laravel-htmx#8]
Why did you choose to re-invent fragments istead of using the ones added inside laravel directly?

**Comment by davidjr82** [comment]
The one of Laravel compiles the full blade file and then extract the fragment. This one extracts the fragment and only compiles this part of the full blade template.

**Comment by wizzymore** [comment]
I was susping that eas the approach used by laravel, really got into some nasty bugs.

Thanks a lot, nice package
